Button that open edit mode on debate page
AletheiaFact/aletheia pull request #1348
Opened 2024-08-14 17:57 UTC by Toxin4

Creation of a button that open the edit mode on the debate page
![image](https://github.com/user-attachments/assets/8c715416-df35-40fc-9458-06517815c137)
![image](https://github.com/user-attachments/assets/ce8a2283-97ee-46dc-8854-65aace4b28a9)
![image](https://github.com/user-attachments/assets/fc16b26b-5fa1-4dc9-b5e3-15cd1b1ca021)

2024-08-14 18:22 UTC, pepermao requested changes

2024-08-14 18:22 UTC, pepermao commented on src/components/Debate/DebateView.tsx
> +                    {userRole === Roles.Regular ? null : (
The user needs to have a permission equals to admin to have the permission to open the edit debate mode

2024-08-14 18:22 UTC, pepermao commented on src/components/Debate/DebateView.tsx
> +                                paddingLeft: 15,
Suggestion: Since this line resulted in no interface changes we can remove it

2024-08-14 18:22 UTC, pepermao commented on src/components/Debate/DebateView.tsx
> +                                width: "10%",
Question: why the width is settled as 10% ?

2024-08-14 18:22 UTC, pepermao commented on src/components/Debate/DebateView.tsx
> +                                    color: "#ffffff",
chore (non-blocking): utilize our colors file library `colors.white`, and import it from "/styles/colors.ts

2024-08-15 19:14 UTC, thesocialdev commented
@Toxin4 the conversations should be resolved by the reviewers.

2024-09-19 12:39 UTC, pepermao approved these changes

2024-10-07 15:56 UTC, merged