Change all typography antd for muy
AletheiaFact/aletheia pull request #1683
Opened 2024-12-22 03:04 UTC by LuizFNJ

# Description
*In this PR, I replaced all Ant Design Typography components with MUI, and where necessary, I replaced Ant Design's Col, Row, Affix, and Comment components with their respective MUI equivalents.*

# Testing 
*I only replaced the typographs, but in some components, I also adjusted the responsiveness since I was already working on them.*

*Each component*
- [ ] #1481
- [ ] #1514
- [ ] #1519
- [ ] #1522
- [ ] #1523
- [ ] #1532
- [ ] #1533
- [ ] #1534
- [ ] #1554
- [ ] #1538
- [ ] #1552
- [ ] #1573

*A visual document outlining which visual parts of the site are intended to facilitate testing:*
[teste-typograph.pdf](https://github.com/user-attachments/files/18220636/teste-typograph.pdf)

closes #1481, #1514, #1519, #1522, #1523, #1532, #1533, #1534, #1554, #1538, #1552, #1573

2024-12-22 03:18 UTC, LuizFNJ commented
Question: MUI does not have a specific Comment component, and we would have to combine multiple components to achieve that. In this PR, I simply removed the Comment component, and the layout and functionality continued working. My question is about the necessity of this component.

2024-12-22 03:21 UTC, LuizFNJ commented
On 1024px - Windows laptop, it breaks. Should I move this CTA to the next line, just like on smaller screens?

![Screenshot from 2024-12-21 23-40-30](https://github.com/user-attachments/assets/664d8509-2e29-4876-b78b-17918703a66c)

2024-12-22 03:24 UTC, LuizFNJ commented on src/components/Claim/ClaimView.tsx
> +import { Affix } from "antd";
I am working on this affix.

2025-01-07 16:01 UTC, thesocialdev requested changes

2025-01-07 16:01 UTC, thesocialdev commented on src/components/Claim/ClaimView.tsx
> +                                    <Typography variant="h6" style={{fontFamily:"initial", fontWeight: 700}}>
issue: see below and apply everywhere

2025-01-07 16:01 UTC, thesocialdev commented on src/components/Claim/ClaimView.tsx
> +    useEffect(() => {
question: could you elaborate on why this is needed?

2025-01-08 22:33 UTC, LuizFNJ commented
> On 1024px - Windows laptop, it breaks. Should I move this CTA to the next line, just like on smaller screens?
> 
> ![Screenshot from 2024-12-21 23-40-30](https://private-user-images.githubusercontent.com/124062745/397962000-664d8509-2e29-4876-b78b-17918703a66c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNzQ4MjgsIm5iZiI6MTczNjM3NDUyOCwicGF0aCI6Ii8xMjQwNjI3NDUvMzk3OTYyMDAwLTY2NGQ4NTA5LTJlMjktNDg3Ni1iNzhiLTE3OTE4NzAzYTY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQyMjE1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODE5MmJlYTg0NTBhYWRhZDE5MmRiYWNhNDEwMzM5ZjhiNzViMGE2ZTA0ZGQ2M2JlYTZhMDMxNDZiMjczNmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wdLeb2GZvslQHSlYpp540dSPBktUdZLFwz19Gp0hty0)

resolved:
![Screenshot from 2025-01-08 23-32-21](https://github.com/user-attachments/assets/dca92b0f-9e65-459d-b350-5da33ae40bb3)

2025-01-09 14:26 UTC, LuizFNJ commented on src/components/Footer/AletheiaSocialMediaIcons.tsx
> +        <Grid container item xs={12}
These three components where I added the "item" property were only to stop the warning from appearing, and it doesn't change anything in the Grid's design. I hadn't noticed this before.
![Screenshot from 2025-01-09 15-20-52](https://github.com/user-attachments/assets/719c704d-eee0-40b3-92ed-f56505ae8086)

2025-01-14 13:06 UTC, thesocialdev approved these changes

2025-01-14 13:06 UTC, merged