Logout Action
AletheiaFact/aletheia pull request #517
Opened 2022-06-30 02:13 UTC by caneppelevitor

2022-06-30 08:36 UTC, thesocialdev requested changes

2022-06-30 08:36 UTC, thesocialdev commented on public/locales/pt/menu.json
> +    "logout": "Sair"
Change to "Encerrar Sessão"

2022-06-30 08:36 UTC, thesocialdev commented on src/components/Login/LogoutAction.tsx
> +export function CreateLogoutHandler(deps?: DependencyList) {
The logic is right and your skills are improving very fast. Congrats.

But this way the handlers creates the flow every time the sidebar is rendered, shouldn't we execute the whole logic only when the menu is clicked? That way we avoid unnecessary calls to Ory.

2022-07-01 14:36 UTC, thesocialdev commented
@caneppelevitor something is off, a lot of other commits got into your branch.

2022-07-01 17:51 UTC, caneppelevitor commented
> 



> @caneppelevitor something is off, a lot of other commits got into your branch.

What should I do to fix that?

2022-07-05 09:22 UTC, merged