Version mobile report page
AletheiaFact/aletheia pull request #556
Opened 2022-07-14 13:03 UTC by Keikonichi

Rewriting some properties to make the report page responsive

2022-07-14 13:04 UTC, Keikonichi commented
The report page response is incomplete in screen sizes from 780px to 1200px

2022-07-18 16:30 UTC, thesocialdev requested changes

2022-07-18 16:30 UTC, thesocialdev commented on src/components/ClaimReview/SentenceReportCard.tsx
> +    const SentenceReportCardStyle = styled.div`
Move to its own file as a new component.

2022-07-18 16:30 UTC, thesocialdev commented on src/components/ClaimReview/SentenceReportView.tsx
> +    const CardStyle1 = styled.div`
Use a more specific name and move to its own file.

2022-07-19 11:07 UTC, thesocialdev requested changes

2022-07-19 11:07 UTC, thesocialdev commented on src/components/ClaimReview/SentenceReportCard.tsx
> +    const SentenceReportCardStyle = styled.div`
Move to its own file.

2022-07-19 11:07 UTC, thesocialdev commented on src/components/ClaimReview/SentenceReportView.tsx
> +                                                    secondaryTextColor="#515151"
Use the colors library for every color added.

2022-07-19 11:07 UTC, thesocialdev commented on src/components/ClaimReview/NewCTARegistration.tsx
> +                        className="New-CTA-registration-button"
For the CSS class names, we should use lower case everywhere.

2022-07-19 12:57 UTC, Keikonichi commented on src/components/ClaimReview/NewCTARegistration.tsx
> +                        "AletheiaFact.org é um movimento e plataforma coletivo de verificação de fatos que imagina uma sociedade onde todos podem ter"
This text in Figma is incomplete, how to proceed with the task?

2022-07-19 23:45 UTC, thesocialdev approved these changes

2022-07-19 23:46 UTC, merged