Implementation of Topics.
AletheiaFact/aletheia pull request #686
Opened 2022-08-12 18:53 UTC by caneppelevitor

2022-08-12 18:56 UTC, thesocialdev commented on server/topic/topic.controller.ts
> +        console.log("first");
Remove console.log

2022-08-12 18:57 UTC, thesocialdev commented on server/topic/topic.controller.ts
> +    private readonly logger = new Logger("");
Add a string to the Logger instatiation

2022-08-12 18:57 UTC, caneppelevitor commented on server/topic/topic.controller.ts
> +        console.log("first");
Sorry, it should be a draft PR

2022-08-12 18:57 UTC, thesocialdev commented on server/topic/topic.service.ts
> +                console.log(topic, "Topic");
Remove console.log

2022-08-12 18:59 UTC, thesocialdev commented on src/components/ClaimReview/TopicInput.tsx
> +    console.log(topics);
Remove console.log

2022-08-12 18:59 UTC, thesocialdev commented on src/components/ClaimReview/TopicInput.tsx
> +            <UserAutocomplete
Should we rename the component to just `Autocomplete`?

2022-08-12 19:01 UTC, thesocialdev commented on src/components/ClaimReview/UserAutocomplete.tsx
>      const fetchUserList = async (name) => {
Renaming the component to Autocomplete means that we should pass the `fetchUserList` or the `fetchTopicList` as "data loaders", adding a new prop to the component `dataLoader`

2022-08-12 19:02 UTC, thesocialdev commented on src/components/ClaimReview/form/SelectUser.tsx
> +            mode={name === "usersId" ? "multiple" : "tags"}
pass styled as a prop instead, the component shouldn't care about it's being for a user or a topic

2022-08-16 13:20 UTC, thesocialdev requested changes
- [ ] Change the gear icon to a pencil icon, to indicate that the topics can be edited
- [ ] Change the label "Edit Topics" to "Add Topics"

Question, how do new topics are inserted in the platform?

2022-08-16 15:04 UTC, pepermao commented
> * [x]  Change the gear icon to a pencil icon, to indicate that the topics can be edited
> * [x]  Change the label "Edit Topics" to "Add Topics"
> 
> Question, how do new topics are inserted in the platform?

I documented it in the topic.service code

2022-08-16 17:28 UTC, thesocialdev approved these changes

2022-08-16 17:28 UTC, merged