Create image schema
AletheiaFact/aletheia pull request #701
Opened 2022-08-16 21:15 UTC by pepermao

- create image schema
- create image function
- sync with the history module

2022-08-16 21:16 UTC, pepermao commented
@DuardoN

2022-08-17 02:52 UTC, thesocialdev requested changes

2022-08-17 02:52 UTC, thesocialdev commented on server/image/image.controller.ts
> +    async create(@Body() image, @Req() req) {
The controller is not needed and can be removed.

2022-08-18 20:42 UTC, thesocialdev approved these changes

2022-08-18 21:14 UTC, merged