Update header layout
AletheiaFact/aletheia pull request #740
Opened 2022-09-12 14:29 UTC by ThaisMap

- the search input is fixed in desktop mode
- the login, logout and my account options are located under the user icon in the header
- the logo is now a svg without any fixed padding and can receive any color 
- the sidebar is now a drawer and clicking away will close it
- updated cypress tests

![image](https://user-images.githubusercontent.com/8875518/189679925-13ccb504-f6aa-4cf4-a259-1275f33acb92.png)
![image](https://user-images.githubusercontent.com/8875518/189679993-a80559c6-9ca2-433e-a149-33dfecaebd3b.png)
![image](https://user-images.githubusercontent.com/8875518/189680309-30174a94-f6f9-4a95-8340-aeda426d0722.png)
![image](https://user-images.githubusercontent.com/8875518/189680460-8d5aa47b-58e6-4f3e-8ea6-f787f2f7cb1b.png)

Closes #602

2022-09-12 17:41 UTC, pepermao commented
The height of the header is now 70px, I feel that some header items are oversized, like the height of the search input. In the design the height of this header is 54px, what do you think of reducing this header height and consequently decreasing the items in it proportionally?

![image](https://user-images.githubusercontent.com/73478823/189720709-c12dbd22-5dfe-41c3-a0b3-b866d2f68408.png)

![image](https://user-images.githubusercontent.com/73478823/189719886-bd09a358-84da-4af3-98aa-7d306cfb6307.png)

2022-09-12 19:03 UTC, pepermao requested changes

2022-09-12 19:04 UTC, thesocialdev commented
> When we are in the mobile version, the search component is hidden as it used to be, look at this prototype on the figma improvements page
> 
> ![image](https://user-images.githubusercontent.com/73478823/189723990-a211997e-4186-42a1-a345-aefca40fc046.png)

This is not desirable, the mockup shouldn't be considered. The reason is because the header is too big and will take too much space from the screen.

2022-09-13 16:16 UTC, pepermao commented
The last question, @thesocialdev, @ThaisMap should make the header fixed now that it takes up a small part of the screen?

2022-09-15 12:16 UTC, merged