Depriving Regular Users of Acess The Platform When It is Private
AletheiaFact/aletheia pull request #997
Opened 2023-09-14 15:31 UTC by caneppelevitor

Closes #966

2023-09-14 16:49 UTC, thesocialdev requested changes

2023-09-14 16:49 UTC, thesocialdev commented on server/auth/session.guard.ts
> +    checkRole(request, response, isPublic) {
suggestion: most of the logic is also used in the `next()` function, maybe you should consolidate them into a single function.

2023-09-14 18:00 UTC, pepermao commented on server/auth/session.guard.ts
> +                    session?.identity?.traits?.role === "regular" &&
suggestion: Use `Roles` enum

2023-09-15 14:53 UTC, thesocialdev approved these changes

2023-09-15 14:53 UTC, merged